### ISSUE TITLE
Progressive page loading 

### ISSUE THREAD

**Issue by adamhathcock** [codedread/kthoom#12]
I noticed the decompression supports forward only streams (I think)

Could the loading of images also be progressive in that i can view the first page ASAP instead of waiting for everything to be loaded?

**Comment by codedread** [comment]
This made me chuckle because I'm going to write a blog post about it :-)

I originally refactored the code for _this_ _very_ _reason_ because loading over Google Drive was sooo slow.  Once I had coded it all up, I discovered that not all comic book archives are stored in the correct page order.  In fact, in a significant number of archives that I sampled, the first page in the zip/rar file is _not_ the first page of the comic book.  All comic book readers must:  a) unzip the entire file, b) sort all pages by their filenames, c) display the first page based on the filename.

Of course this is horrible, but probably no one ever thought about streaming comic book archive files before :-/

So ultimately, the unarchivers progressively unarchive the file, then kthoom does the sorting after the unarchiving is all complete.  It saves some small amount of time (because the expensive part of the unarchiving can happen progressively as it downloads), but it is definitely not the win I was hoping for :(

If I could guarantee that the archives have properly stored the bytes in page order, then this is a really easy code change (just remove the sorting inside kthoom).

**Comment by adamhathcock** [comment]
I'm impressed you have streaming unrar and unzip in Javascript :)   I've done the same for C# (http://github.com/adamhathcock/sharpcompress) but I've always needed a cross-platform viewer.  I wrote a silverlight one years ago with progressive loading.   It was nice opening a large file and see the images pop in.

You're right, you'll have to sort on the fly.  If something is out of order, just put it in order as you read in the entries.  Don't worry if someone created the archive with files out of order.

**Comment by codedread** [comment]
I've added some preliminary support for progressive loading in kthoom.  If the ComicInfo.xml has the following element:

  <ArchiveFileInfo xmlns="http://www.codedread.com/sop" optimizedForStreaming="true" />

Then kthoom will show the pages immediately upon extraction.

"sop" stands for "stream-optimized publication".

**Comment by codedread** [comment]
Calling this implemented now.  It does require the comic book archive file to be re-archived and specify that it is optimized for streaming in its metadata file.
